# Generated by Django 5.2.5 on 2025-08-21 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=100, verbose_name='ACCESS TOKEN')),
                ('refresh_token', models.CharField(max_length=100, verbose_name='REFRESH TOKEN')),
                ('expires_in', models.DateTimeField(verbose_name='EXPIRES IN')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '토큰 관리',
            },
        ),
    ]
